// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa0YS50vSE4CrsCBZ-W0bT5ocYVqnr0bk',
    appId: '1:708458170314:web:4818af2f75c69f454c3133',
    messagingSenderId: '708458170314',
    projectId: 'dietlist-42c42',
    authDomain: 'dietlist-42c42.firebaseapp.com',
    storageBucket: 'dietlist-42c42.appspot.com',
    measurementId: 'G-WSBZKX5TGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaEhl0iJZyv89ptnGQdz7IPKqDzRMm7-E',
    appId: '1:708458170314:android:c346de26988a650a4c3133',
    messagingSenderId: '708458170314',
    projectId: 'dietlist-42c42',
    storageBucket: 'dietlist-42c42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHU4Hwe25zkWZkmAivnCcGdPOe49Ztvqc',
    appId: '1:708458170314:ios:5b3cfdc08ae04c104c3133',
    messagingSenderId: '708458170314',
    projectId: 'dietlist-42c42',
    storageBucket: 'dietlist-42c42.appspot.com',
    iosClientId: '708458170314-sdjmtu3qve09e1erilgrsidqpa3nmpde.apps.googleusercontent.com',
    iosBundleId: 'com.drobotuhina.dietList',
  );
}
